# Generated by Django 4.2.7 on 2024-02-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemDIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='menu_images/')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image2', models.ImageField(upload_to='menu_images/')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
            ],
        ),
    ]
